baseURL = "https://www.acekyd.com/"
languageCode = "en-us"
title = "Abati Adewale"

theme = "coder"
defaultcontentlanguage = "en"
paginate = 10
canonifyurls = true

pygmentsstyle = "monokai" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

disqusShortname = "acekyd-github" # Enable or disable Disqus.
googleAnalytics = "UA-105301496-1"

[params] # theme parameters
    author = "Adewale Abati" # Author's name.
    info = "Hi, I'm Adewale Abati but a lot of people call me Ace. A Web Developer, Advocate, Open Sourcer and YouTuber. I tried to think of something witty to write here but I'd just leave it to your wits. ♠️" # Author's job title or info.
    description = "Adewale Abati also known as Ace is a web developer, developer advocate, open sourcer and youtuber from Lagos, Nigeria." # Site description.
    keywords = "acekyd, adewale abati, blog, developer, personal, adewale ace " # Site keywords.
    avatarurl = "images/ace-image.png" # Contain the path of the optional avatar in the static folder.
    logourl = "images/logo.png" # Contain the path to a logo.

    footercontent = "Ace is a Lifestyle." # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = ["css/style.css"]

    # RTL support
    rtl = false

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github-square"
    weight = 1
    url = "https://github.com/acekyd/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter-square"
    weight = 2
    url = "https://twitter.com/ace_kyd/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/acekyd/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 4
    url = "https://www.instagram.com/acekyd/"
[[params.social]]
    name = "YouTube"
    icon = "fab fa-youtube"
    weight = 5
    url = "https://www.youtube.com/acekyd/"

[[params.social]]
    name = "Twitch"
    icon = "fab fa-twitch"
    weight = 5
    url = "https://www.twitch.tv/elpunish3rr"

[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow"
    weight = 6
    url = "https://stackoverflow.com/users/1945274/acekyd"

[[params.social]]
    name = "Patreon"
    icon = "fab fa-patreon"
    weight = 7
    url = "https://www.patreon.com/acekyd"

[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 7
    url = "https://www.medium.com/@acekyd"

# Menu links

[[menu.main]]
    name = "Merch"
    weight = 1
    url  = "https://www.printivo.com/store/ace"

[[menu.main]]
    name = "Talks"
    weight = 1
    url  = "/talks/"

[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"

[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"

[[menu.main]]
    name = "Contact"
    weight = 4
    url = "mailto:adewale@acekyd.com"